# Generated by Django 5.2.11 on 2026-03-12 18:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'autor (obligatori)", max_length=100, verbose_name='Nom')),
                ('cognoms', models.CharField(help_text="Cognoms de l'autor (obligatori)", max_length=200, verbose_name='Cognoms')),
                ('email', models.EmailField(help_text="Correu electrònic de l'autor (únic)", max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Si us plau, introdueix un correu electrònic vàlid.')], verbose_name='Correu electrònic')),
                ('data_naixement', models.DateField(blank=True, help_text="Data de naixement de l'autor", null=True, verbose_name='Data de naixement')),
                ('càrrec', models.CharField(blank=True, help_text="Càrrec o posició de l'autor", max_length=100, null=True, verbose_name='Càrrec')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(help_text='Títol del recurs (obligatori)', max_length=200, verbose_name='Títol')),
                ('descripcio', models.TextField(blank=True, help_text='Descripció del recurs', null=True, verbose_name='Descripció')),
                ('categoria', models.CharField(choices=[('TEC', 'Tecnologia'), ('EDU', 'Educació'), ('SAL', 'Salut'), ('ENT', 'Entreteniment'), ('ALT', 'Altres')], default='ALT', help_text='Categoria del recurs', max_length=3, verbose_name='Categoria')),
                ('data_publicacio', models.DateTimeField(default=django.utils.timezone.now, help_text='Data en què es va publicar el recurs', verbose_name='Data de Publicació')),
                ('is_activ', models.BooleanField(default=True, help_text='Indica si el recurs està actiu', verbose_name='Està Actiu')),
            ],
            options={
                'verbose_name': 'Recurs',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
