# Generated by Django 6.0.2 on 2026-03-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurs',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Autor del recurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='api.autor', verbose_name='Autor'),
        ),
    ]
